[package]
name = "AOC2020"
version = "0.1.0"
authors = ["Jason Legler <j@legler.io>"]
edition = "2018"

[dependencies]

[lib]
name = "input_file"
path = "lib/input-file/src/lib.rs"

[[bin]]
name = "day-1"
path = "src/day-1/src/main.rs"

[[bin]]
name = "day-2"
path = "src/day-2/src/main.rs"
